import { LiaEdit } from "react-icons/lia";
import { MdDelete } from "react-icons/md";
import { AiOutlineDislike } from "react-icons/ai";
import { AiOutlineStar } from "react-icons/ai";
import { AiFillPrinter } from "react-icons/ai";
import { AiOutlineLike } from "react-icons/ai";
import { BiLike } from "react-icons/bi";

export const progress = [
  {
    id: 1,
    link: "",
    title: "",
    students: 13,
    students_progress: 13,
    start_Date: "2020-06-10",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "red",
  },
  {
    id: 2,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 11,
    students_progress: 76,
    start_Date: "2020-06-29",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },
  {
    id: 3,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 12,
    students_progress: 99,
    start_Date: "2020-08-12",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },
  {
    id: 4,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 39,
    students_progress: 68,
    start_Date: "2020-09-15",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "purple",
  },
  {
    id: 5,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 31,
    students_progress: 70,
    start_Date: "2020-09-21",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "purple",
  },
  {
    id: 6,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 18,
    students_progress: 94,
    start_Date: "2020-09-28",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },
  {
    id: 7,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 11,
    students_progress: 78,
    start_Date: "2020-10-11",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },
  {
    id: 8,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 22,
    students_progress: 47,
    start_Date: "2020-11-02",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "orange",
  },
  {
    id: 9,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 18,
    students_progress: 67,
    start_Date: "2020-11-02",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "purple",
  },
  {
    id: 10,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 6,
    students_progress: 53,
    start_Date: "2020-11-02",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "purple",
  },
  {
    id: 11,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 9,
    students_progress: 44,
    start_Date: "2020-11-02",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "orange",
  },
  {
    id: 12,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 1,
    students_progress: 100,
    start_Date: "2021-06-23",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },
  {
    id: 13,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 2,
    students_progress: 50,
    start_Date: "2021-09-17",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "orange",
  },
  {
    id: 14,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 1,
    students_progress: 15,
    start_Date: "2021-10-18",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "red",
  },
  {
    id: 15,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 1,
    students_progress: -8,
    start_Date: "2022-02-19",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },

  {
    id: 16,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 1,
    students_progress: 100,
    start_Date: "2022-03-25",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },

  {
    id: 17,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 2,
    students_progress: 100,
    start_Date: "2022-05-13",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },

  {
    id: 18,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 7,
    students_progress: 76,
    start_Date: "2022-05-16	",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },

  {
    id: 19,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 2,
    students_progress: 94,
    start_Date: "2023-01-16	",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },

  {
    id: 20,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 11,
    students_progress: 76,
    start_Date: "",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },

  {
    id: 21,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 11,
    students_progress: 94,
    start_Date: "",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },

  {
    id: 22,
    link: "B1J3Y20",
    title: "Modern Web App Development",
    students: 11,
    students_progress: 92,
    start_Date: "",
    freeCollected: "17,220",
    freeDue: "116,066",
    prints: AiFillPrinter,
    bgColor: "green",
  },
];

export const enqueryList = [
  {
    id: 1,
    names: "mario cota",
    Email: "mario.cota@smartbuddy.mx",
    Mobile: "+523330136312",
    CNIC: 3320423762,
    FourCourse: "	Android Application Development",
    PrefTime: "	04:33:07",
    EmailStatus: "open",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 2,
    names: "Mahmoud",
    Email: "test@test.com",
    Mobile: "+0012-2232343",
    CNIC: 32343 - 4355550 - 0,
    FourCourse: "المستوي الاول - العربية بين يديك",
    PrefTime: "	1:00 AM",
    EmailStatus: "open",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 3,
    names: "SCHOOLS",
    Email: "sudambik@gmail.com",
    Mobile: "+gtyudtrxvbn",
    CNIC: 0 - 9886675644,
    FourCourse: "WEB SCRAPPING",
    PrefTime: "	03:20:43",
    EmailStatus: "open",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 4,
    names: "Seyit Ömer",
    Email: "seyitomerballi@gmail.com",
    Mobile: "ghjghjghjghj",
    CNIC: 3320423762,
    FourCourse: "	Android Application Development",
    PrefTime: "	10:46:15",
    EmailStatus: "open",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 5,
    names: "jhvjv",
    Email: "jhjjhvjv@gmail.com",
    Mobile: "+76765757",
    CNIC: 67576575675,
    FourCourse: "WEB SCRAPPING",
    PrefTime: "	04:51:44",
    EmailStatus: "open",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 6,
    names: "OOI GUAN LIN",
    Email: "ooiguanlin@ntucac.com",
    Mobile: "+0987-6000000",
    CNIC: 98765 - 9876543 - 5,
    FourCourse: "Android Application Development",
    PrefTime: "	5:00 PM",
    EmailStatus: "open",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 7,
    names: "Jen",
    Email: "vispevidra@biyac.com",
    Mobile: "+123123",
    CNIC: 13123,
    FourCourse: "Modern Web App Development",
    PrefTime: "10:22:10",
    EmailStatus: "open",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 8,
    names: "jon",
    Email: "zafyokostu@biyac.com",
    Mobile: "+123123123123",
    CNIC: 12123123123123,
    FourCourse: "WEB SCRAPPING",
    PrefTime: "	11:00:59",
    EmailStatus: "open",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 9,
    names: "	Vinto",
    Email: "lajojur.husitu@vintomaper.com",
    Mobile: "+	4444-33234	",
    CNIC: 3312 - 124123,
    FourCourse: "Adobe Illustrator",
    PrefTime: "	03:16:59	",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 10,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 11,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 12,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 13,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 14,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 15,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 16,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 17,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 18,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 19,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 20,
    names: "Ben",
    Email: "xsbifikaa@uniromax.com",
    Mobile: "+	332-2222",
    CNIC: 333 - 1111,
    FourCourse: "	Advanced Graphics Designing",
    PrefTime: "	05:56:01",
    EmailStatus: "close",
    Action: LiaEdit,
    delete: MdDelete,
  },
];

export const getUsers = function (page, limit) {
  const array = [];
  for (let i = (page - 1) * limit; i < page * limit && enqueryList[i]; i++) {
    array.push(enqueryList[i]);
  }
  return array;
};

export const getLength = function () {
  return enqueryList.length;
};

export const studentss = [
  {
    id: 1,
    names: "reda",
    RedNo: "SIFSD01-Ar-13-21-1",
    Email: "reda@yahoo.com",
    Mobile: "0121-3232400",
    CNIC: "22112-3243243-4",
    Course: "Arabic",
    Batch: "Arabic 001",
    Action: LiaEdit,
    Like: BiLike,
  },

  {
    id: 2,
    names: "reda",
    RedNo: "SIFSD01-AD-2-21-162",
    Email: "aa@test.com",
    Mobile: "0012-1324324",
    CNIC: "23232-4000000-0",
    Course: "Android Application Development",
    Batch: "B1SEP20",
    Action: LiaEdit,
    Like: BiLike,
  },

  {
    id: 3,
    names: "asdsad",
    RedNo: "SIFSD01-AD-Select Batch-21-1",
    Email: "adsad@dddd.com",
    Mobile: "0432-4234234",
    CNIC: "43242-3423423-4",
    Course: "Android Application Development",
    Batch: "B1SEP20",
    Action: LiaEdit,
    Like: BiLike,
  },

  {
    id: 4,
    names: "Hasan",
    RedNo: "SIFSD01-AD-Select Batch-21-166",
    Email: "admin@gmail.com",
    Mobile: "0243-5467687",
    CNIC: "21345-3676543-2",
    Course: "Android Application Development",
    Batch: "B1SEP20",
    Action: LiaEdit,
    Like: BiLike,
  },

  {
    id: 5,
    names: "xyz",
    RedNo: "SIFSD01-AD-2-21-1",
    Email: "XYZ@GMAIL.COM",
    Mobile: "0989-9821983	",
    CNIC: "23232-4000000-0",
    Course: "Android Application Development",
    Batch: "B1SEP20",
    Action: LiaEdit,
    Like: BiLike,
  },

  {
    id: 6,
    names: "reda",
    RedNo: "SIFSD01-AD-2-21-162",
    Email: "aa@test.com",
    Mobile: "0012-1324324",
    CNIC: "23232-4000000-0",
    Course: "Android Application Development",
    Batch: "B1SEP20",
    Action: LiaEdit,
    Like: BiLike,
  },

  {
    id: 7,
    names: "reda",
    RedNo: "SIFSD01-AD-2-21-162",
    Email: "aa@test.com",
    Mobile: "0012-1324324",
    CNIC: "23232-4000000-0",
    Course: "Android Application Development",
    Batch: "B1SEP20",
    Action: LiaEdit,
    Like: BiLike,
  },

  {
    id: 8,
    names: "reda",
    RedNo: "SIFSD01-AD-2-21-162",
    Email: "aa@test.com",
    Mobile: "0012-1324324",
    CNIC: "23232-4000000-0",
    Course: "Android Application Development",
    Batch: "B1SEP20",
    Action: LiaEdit,
    Like: BiLike,
  },

  {
    id: 9,
    names: "reda",
    RedNo: "SIFSD01-AD-2-21-162",
    Email: "aa@test.com",
    Mobile: "0012-1324324",
    CNIC: "23232-4000000-0",
    Course: "Android Application Development",
    Batch: "B1SEP20",
    Action: LiaEdit,
    Like: BiLike,
  },

  {
    id: 10,
    names: "reda",
    RedNo: "SIFSD01-AD-2-21-162",
    Email: "aa@test.com",
    Mobile: "0012-1324324",
    CNIC: "23232-4000000-0",
    Course: "Android Application Development",
    Batch: "B1SEP20",
    Action: LiaEdit,
    Like: BiLike,
  },
  {
    id: 11,
    names: "reda",
    RedNo: "SIFSD01-AD-2-21-162",
    Email: "aa@test.com",
    Mobile: "0012-1324324",
    CNIC: "23232-4000000-0",
    Course: "Android Application Development",
    Batch: "B1SEP20",
    Action: LiaEdit,
    Like: BiLike,
  },
];
export const active = [
  {
    id: 1,
    link: "Marquis Menjivar",
    title: "SIFSD01-WD1-20-2",
    students: "marquis_menjivar@gmail.com",
    students_progress: "6368-6047073",
    start_Date: "89808-7574318-8",
    freeCollected: "Modern Web App Development",
    freeDue: "B1SEP20",
    edit: LiaEdit,
    delete: MdDelete,
    dislike: AiOutlineDislike,
  },

  {
    id: 2,
    link: " Georgianna Schroeder",
    title: "SIFSD01-AD3-20-1",
    students: " georgianna_schroeder@gmail.com",
    students_progress: 2252 - 5825236,
    start_Date: "69133-6276730-8",
    freeCollected: "Android Application Development",
    freeDue: "B1J3Y20",
    edit: LiaEdit,
    delete: MdDelete,
    dislike: AiOutlineDislike,
  },

  {
    id: 3,
    link: "Buffy Volkman",
    title: " SIFSD01-AD3-20-4",
    students: " buffy_volkman@gmail.com",
    students_progress: 2252 - 5825236,
    start_Date: "39410-7167504-4 ",
    freeCollected: "Android Application Development",
    freeDue: "B1AUG20",
    edit: LiaEdit,
    delete: MdDelete,
    dislike: AiOutlineDislike,
  },

  {
    id: 4,
    link: "Georgianna Paris ",
    title: "SIFSD01-AD3-20-5",
    students: "georgianna_paris@gmail.com",
    students_progress: 7849 - 1603849,
    start_Date: "94339-9031937-4",
    freeCollected: "Android Application Development",
    freeDue: "B1AUG20",
    edit: LiaEdit,
    delete: MdDelete,
    dislike: AiOutlineDislike,
  },

  {
    id: 5,
    link: "Georgianna Paris ",
    title: "SIFSD01-AD3-20-5",
    students: "georgianna_paris@gmail.com",
    students_progress: 7849 - 1603849,
    start_Date: "94339-9031937-4",
    freeCollected: "Android Application Development",
    freeDue: "B1AUG20",
    edit: LiaEdit,
    delete: MdDelete,
    dislike: AiOutlineDislike,
  },

  {
    id: 6,
    link: "Georgianna Paris ",
    title: "SIFSD01-AD3-20-5",
    students: "georgianna_paris@gmail.com",
    students_progress: 7849 - 1603849,
    start_Date: "94339-9031937-4",
    freeCollected: "Android Application Development",
    freeDue: "B1AUG20",
    edit: LiaEdit,
    delete: MdDelete,
    dislike: AiOutlineDislike,
  },

  {
    id: 7,
    link: "Georgianna Paris ",
    title: "SIFSD01-AD3-20-5",
    students: "georgianna_paris@gmail.com",
    students_progress: 7849 - 1603849,
    start_Date: "94339-9031937-4",
    freeCollected: "Android Application Development",
    freeDue: "B1AUG20",
    edit: LiaEdit,
    delete: MdDelete,
    dislike: AiOutlineDislike,
  },

  {
    id: 8,
    link: "Georgianna Paris ",
    title: "SIFSD01-AD3-20-5",
    students: "georgianna_paris@gmail.com",
    students_progress: 7849 - 1603849,
    start_Date: "94339-9031937-4",
    freeCollected: "Android Application Development",
    freeDue: "B1AUG20",
    edit: LiaEdit,
    delete: MdDelete,
    dislike: AiOutlineDislike,
  },

  {
    id: 9,
    link: "Georgianna Paris ",
    title: "SIFSD01-AD3-20-5",
    students: "georgianna_paris@gmail.com",
    students_progress: 7849 - 1603849,
    start_Date: "94339-9031937-4",
    freeCollected: "Android Application Development",
    freeDue: "B1AUG20",
    edit: LiaEdit,
    delete: MdDelete,
    dislike: AiOutlineDislike,
  },

  {
    id: 10,
    link: "Georgianna Paris ",
    title: "SIFSD01-AD3-20-5",
    students: "georgianna_paris@gmail.com",
    students_progress: 7849 - 1603849,
    start_Date: "94339-9031937-4",
    freeCollected: "Android Application Development",
    freeDue: "B1AUG20",
    edit: LiaEdit,
    delete: MdDelete,
    dislike: AiOutlineDislike,
  },
];

export const Batches_study = [
  {
    id: 1,
    link: "	B1J3Y20",
    title: "Modern Web App Development",
    students: "	5:30 PM",
    students_progress: "2020-06-10",
    start_Date: "2020-10-01",
    freeCollected: "	Tyisha Geddes",
    freeDue: "	50 %",
    edit: LiaEdit,
    dislike: AiOutlineLike,
  },

  {
    id: 2,
    link: "	B1J3Y20",
    title: "Modern Web App Development",
    students: "	5:30 PM",
    students_progress: "2020-06-10",
    start_Date: "2020-10-01",
    freeCollected: "	Tyisha Geddes",
    freeDue: "	50 %",
    edit: LiaEdit,
    dislike: AiOutlineLike,
  },

  {
    id: 3,
    link: "	B1J3Y20",
    title: "Modern Web App Development",
    students: "	5:30 PM",
    students_progress: "2020-06-10",
    start_Date: "2020-10-01",
    freeCollected: "	Tyisha Geddes",
    freeDue: "	50 %",
    edit: LiaEdit,
    dislike: AiOutlineLike,
  },

  {
    id: 4,
    link: "	B1J3Y20",
    title: "Modern Web App Development",
    students: "	5:30 PM",
    students_progress: "2020-06-10",
    start_Date: "2020-10-01",
    freeCollected: "	Tyisha Geddes",
    freeDue: "	50 %",
    edit: LiaEdit,
    dislike: AiOutlineLike,
  },

  {
    id: 5,
    link: "	B1J3Y20",
    title: "Modern Web App Development",
    students: "	5:30 PM",
    students_progress: "2020-06-10",
    start_Date: "2020-10-01",
    freeCollected: "	Tyisha Geddes",
    freeDue: "	50 %",
    edit: LiaEdit,
    dislike: AiOutlineLike,
  },

  {
    id: 6,
    link: "	B1J3Y20",
    title: "Modern Web App Development",
    students: "	5:30 PM",
    students_progress: "2020-06-10",
    start_Date: "2020-10-01",
    freeCollected: "	Tyisha Geddes",
    freeDue: "	50 %",
    edit: LiaEdit,
    dislike: AiOutlineLike,
  },

  {
    id: 7,
    link: "	B1J3Y20",
    title: "Modern Web App Development",
    students: "	5:30 PM",
    students_progress: "2020-06-10",
    start_Date: "2020-10-01",
    freeCollected: "	Tyisha Geddes",
    freeDue: "	50 %",
    edit: LiaEdit,
    dislike: AiOutlineLike,
  },

  {
    id: 8,
    link: "	B1J3Y20",
    title: "Modern Web App Development",
    students: "	5:30 PM",
    students_progress: "2020-06-10",
    start_Date: "2020-10-01",
    freeCollected: "	Tyisha Geddes",
    freeDue: "	50 %",
    edit: LiaEdit,
    dislike: AiOutlineLike,
  },

  {
    id: 9,
    link: "	B1J3Y20",
    title: "Modern Web App Development",
    students: "	5:30 PM",
    students_progress: "2020-06-10",
    start_Date: "2020-10-01",
    freeCollected: "	Tyisha Geddes",
    freeDue: "	50 %",
    edit: LiaEdit,
    dislike: AiOutlineLike,
  },

  {
    id: 10,
    link: "	B1J3Y20",
    title: "Modern Web App Development",
    students: "	5:30 PM",
    students_progress: "2020-06-10",
    start_Date: "2020-10-01",
    freeCollected: "	Tyisha Geddes",
    freeDue: "	50 %",
    edit: LiaEdit,
    dislike: AiOutlineLike,
  },
];

export const foculties = [
  {
    id: 1,
    link: "	Tyisha Geddes",
    title: "	9271-2773114",
    students: "tyisha_geddes@gmail.com",
    students_progress: "Modern Web App Development",
    star: AiOutlineStar,
    freeCollected: "Approved",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 2,
    link: "	Tyisha Geddes",
    title: "	9271-2773114",
    students: "tyisha_geddes@gmail.com",
    students_progress: "	 Modern Web App Development",
    star: AiOutlineStar,
    freeCollected: "Approved",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 3,
    link: "	Tyisha Geddes",
    title: "	9271-2773114",
    students: "tyisha_geddes@gmail.com",
    students_progress: "	  Modern Web App Development",
    star: AiOutlineStar,
    freeCollected: "Approved",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 4,
    link: "	Tyisha Geddes",
    title: "	9271-2773114",
    students: "tyisha_geddes@gmail.com",
    students_progress: " Modern Web App Development",
    star: AiOutlineStar,
    freeCollected: "Approved",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 5,
    link: "	Tyisha Geddes",
    title: "	9271-2773114",
    students: "tyisha_geddes@gmail.com",
    students_progress: "	    Modern Web App Development",
    star: AiOutlineStar,
    freeCollected: "Approved",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 6,
    link: "	Tyisha Geddes",
    title: "	9271-2773114",
    students: "tyisha_geddes@gmail.com",
    students_progress: "	    Modern Web App Development",
    star: AiOutlineStar,
    freeCollected: "Approved",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 7,
    link: "	Tyisha Geddes",
    title: "	9271-2773114",
    students: "tyisha_geddes@gmail.com",
    students_progress: "	    Modern Web App Development",
    star: AiOutlineStar,
    freeCollected: "Approved",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 8,
    link: "	Tyisha Geddes",
    title: "	9271-2773114",
    students: "tyisha_geddes@gmail.com",
    students_progress: "	    Modern Web App Development",
    star: AiOutlineStar,
    freeCollected: "Approved",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 9,
    link: "	Tyisha Geddes",
    title: "	9271-2773114",
    students: "tyisha_geddes@gmail.com",
    students_progress: "	    Modern Web App Development",
    star: AiOutlineStar,
    freeCollected: "Approved",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 10,
    link: "	Tyisha Geddes",
    title: "	9271-2773114",
    students: "tyisha_geddes@gmail.com",
    students_progress: "	 Modern Web App Development",
    star: AiOutlineStar,
    freeCollected: "Approved",
    edit: LiaEdit,
    delete: MdDelete,
  },
];

export const Courses_time = [
  {
    id: 1,
    link: "Android Application Development",
    title: "Development",
    students: "120 Days",
    students_progress: "	25000",
    star: 142,
    freeCollected: "7",
    number: "13",
    email_status: "open",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 2,
    link: "Android Application Development",
    title: "Development",
    students: "120 Days",
    students_progress: "	25000",
    star: 142,
    freeCollected: "7",
    number: "13",
    email_status: "open",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 3,
    link: "Android Application Development",
    title: "Development",
    students: "120 Days",
    students_progress: "	25000",
    star: 142,
    freeCollected: "7",
    number: "13",
    email_status: "open",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 4,
    link: "Android Application Development",
    title: "Development",
    students: "120 Days",
    students_progress: "	25000",
    star: 142,
    freeCollected: "7",
    number: "13",
    email_status: "open",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 5,
    link: "Android Application Development",
    title: "Development",
    students: "120 Days",
    students_progress: "	25000",
    star: 142,
    freeCollected: "7",
    number: "13",
    email_status: "open",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 6,
    link: "Android Application Development",
    title: "Development",
    students: "120 Days",
    students_progress: "	25000",
    star: 142,
    freeCollected: "7",
    number: "13",
    email_status: "open",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 7,
    link: "Android Application Development",
    title: "Development",
    students: "120 Days",
    students_progress: "	25000",
    star: 142,
    freeCollected: "7",
    number: "13",
    email_status: "open",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 8,
    link: "Android Application Development",
    title: "Development",
    students: "120 Days",
    students_progress: "	25000",
    star: 142,
    freeCollected: "7",
    number: "13",
    email_status: "open",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 9,
    link: "Android Application Development",
    title: "Development",
    students: "120 Days",
    students_progress: "	25000",
    star: 142,
    freeCollected: "7",
    number: "13",
    email_status: "open",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 10,
    link: "Android Application Development",
    title: "Development",
    students: "120 Days",
    students_progress: "	25000",
    star: 142,
    freeCollected: "7",
    number: "13",
    email_status: "open",
    edit: LiaEdit,
    delete: MdDelete,
  },
];

export const Event_book = [
  {
    id: 1,
    link: "",
    title: "1",
    students: "bnsabd",
    students_progress: "demo1@gmail.com",
    star: "0561-8171241",
    freeCollected: "88798-9988989-8",
    email_status: "open",
    delete: MdDelete,
  },

  {
    id: 2,
    link: "",
    title: "1",
    students: "bnsabd",
    students_progress: "demo1@gmail.com",
    star: "0561-8171241",
    freeCollected: "88798-9988989-8",
    email_status: "open",
    delete: MdDelete,
  },

  {
    id: 3,
    link: "",
    title: "1",
    students: "bnsabd",
    students_progress: "demo1@gmail.com",
    star: "0561-8171241",
    freeCollected: "88798-9988989-8",
    email_status: "open",
    delete: MdDelete,
  },

  {
    id: 4,
    link: "",
    title: "1",
    students: "bnsabd",
    students_progress: "demo1@gmail.com",
    star: "0561-8171241",
    freeCollected: "88798-9988989-8",
    email_status: "open",
    delete: MdDelete,
  },

  {
    id: 5,
    link: "",
    title: "1",
    students: "bnsabd",
    students_progress: "demo1@gmail.com",
    star: "0561-8171241",
    freeCollected: "88798-9988989-8",
    email_status: "open",
    delete: MdDelete,
  },

  {
    id: 6,
    link: "",
    title: "1",
    students: "bnsabd",
    students_progress: "demo1@gmail.com",
    star: "0561-8171241",
    freeCollected: "88798-9988989-8",
    email_status: "open",
    delete: MdDelete,
  },

  {
    id: 7,
    link: "",
    title: "1",
    students: "bnsabd",
    students_progress: "demo1@gmail.com",
    star: "0561-8171241",
    freeCollected: "88798-9988989-8",
    email_status: "open",
    delete: MdDelete,
  },

  {
    id: 8,
    link: "",
    title: "1",
    students: "bnsabd",
    students_progress: "demo1@gmail.com",
    star: "0561-8171241",
    freeCollected: "88798-9988989-8",
    email_status: "open",
    delete: MdDelete,
  },

  {
    id: 9,
    link: "",
    title: "1",
    students: "bnsabd",
    students_progress: "demo1@gmail.com",
    star: "0561-8171241",
    freeCollected: "88798-9988989-8",
    email_status: "open",
    delete: MdDelete,
  },

  {
    id: 10,
    link: "",
    title: "1",
    students: "bnsabd",
    students_progress: "demo1@gmail.com",
    star: "0561-8171241",
    freeCollected: "88798-9988989-8",
    email_status: "open",
    delete: MdDelete,
  },
];

export const Event_book_two = [
  {
    id: 1,
    title: "2 Days Workshop on Freelancing",
    students:
      "The Freelancing workshop was held on the Friday, January, 2020. The venue was Stepup IT Solutions. Workshop was conducted by the multi-talented, Mr Abu ul Hasan, fellow GCUF student, currently in the teaching field of computer science. He is an active freelance developer and adept outworker had years of experience with free lancing and has worked at Android Applications, a professional, minority owned IT service company. The process of learning is undone until you have the will to teach and carry forward; Abu ul Hasan’ success in free...",
    edit: LiaEdit,
    delete: MdDelete,
  },

  {
    id: 2,
    title: "2 Days Workshop on Freelancing",
    students:
      "The Freelancing workshop was held on the Friday, January, 2020. The venue was Stepup IT Solutions. Workshop was conducted by the multi-talented, Mr Abu ul Hasan, fellow GCUF student, currently in the teaching field of computer science. He is an active freelance developer and adept outworker had years of experience with free lancing and has worked at Android Applications, a professional, minority owned IT service company. The process of learning is undone until you have the will to teach and carry forward; Abu ul Hasan’ success in free...",
    edit: LiaEdit,
    delete: MdDelete,
  },
];

export const Email_function = [
  {
    id: 1,
    title: "Development",
    edit: LiaEdit,
    delete: MdDelete,
  },
  {
    id: 2,
    title: "Development",
    edit: LiaEdit,
    delete: MdDelete,
  },
];
